import { SubtitleCue } from '../types';

export function convertToSrt(cues: SubtitleCue[]): string {
  return cues
    .map((cue, index) => {
      const start = formatSrtTime(cue.startTime);
      const end = formatSrtTime(cue.endTime);
      return `${index + 1}\n${start} --> ${end}\n${cue.text}\n`;
    })
    .join('\n');
}

export function convertToVtt(cues: SubtitleCue[]): string {
  const header = 'WEBVTT - Generated by Sakura Movie Recap\n\n';
  const body = cues
    .map((cue, index) => {
      const start = formatVttTime(cue.startTime);
      const end = formatVttTime(cue.endTime);
      return `${index + 1}\n${start} --> ${end}\n${cue.text}\n`;
    })
    .join('\n');
  return header + body;
}

function formatSrtTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')},${ms.toString().padStart(3, '0')}`;
}

export function formatSeconds(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}

export function parseTimestampToSeconds(timeStr: string): number {
  if (!timeStr) return 0;
  const normalized = timeStr.trim().replace(',', '.');
  const parts = normalized.split(':');
  if (parts.length === 3) {
    const h = parseFloat(parts[0]) || 0;
    const m = parseFloat(parts[1]) || 0;
    const s = parseFloat(parts[2]) || 0;
    return h * 3600 + m * 60 + s;
  }
  if (parts.length === 2) {
    const m = parseFloat(parts[0]) || 0;
    const s = parseFloat(parts[1]) || 0;
    return m * 60 + s;
  }
  return parseFloat(normalized) || 0;
}

export function parseSrtToCues(srtText: string): SubtitleCue[] {
  if (!srtText || !srtText.trim()) return [];
  const normalized = srtText.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const blocks = normalized.split(/\n\n+/);
  const cues: SubtitleCue[] = [];

  for (let i = 0; i < blocks.length; i++) {
    const block = blocks[i].trim();
    if (!block) continue;
    const lines = block.split('\n').map((l) => l.trim()).filter((l) => l.length > 0);
    if (lines.length < 2) continue;

    // Line 0 is often cue index, but can sometimes be timestamp
    let timeLine = '';
    let textStartIndex = 1;

    if (lines[0].includes('-->')) {
      timeLine = lines[0];
      textStartIndex = 1;
    } else if (lines[1] && lines[1].includes('-->')) {
      timeLine = lines[1];
      textStartIndex = 2;
    }

    if (!timeLine) continue;

    const [startRaw, endRaw] = timeLine.split('-->').map((s) => s.trim());
    const startSec = parseTimestampToSeconds(startRaw);
    const endSec = parseTimestampToSeconds(endRaw);
    const text = lines.slice(textStartIndex).join(' ').trim();

    if (text) {
      cues.push({
        id: cues.length + 1,
        startTime: Math.round(startSec * 10) / 10,
        endTime: Math.round(Math.max(startSec + 0.5, endSec) * 10) / 10,
        startDisplay: formatSeconds(startSec),
        endDisplay: formatSeconds(endSec),
        text,
      });
    }
  }

  return cues;
}

export function parseVttToCues(vttText: string): SubtitleCue[] {
  const clean = vttText.replace(/^WEBVTT[^\n]*\n+/i, '');
  return parseSrtToCues(clean);
}

function formatVttTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}.${ms.toString().padStart(3, '0')}`;
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(textarea);
    return ok;
  }
}
